name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda a cada push na branch principal
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # O GitHub fornece esse token automaticamente, não é necessário criar um se você quiser apenas métricas básicas.
          token: ${{ secrets.GITHUB_TOKEN }}
          user: strngrthnall
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
